pool11_inqaba:
  CAP425_4200:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAgacagaNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
#   CAP5160_0:
#     cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAtagagcNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
#     panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
#     sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
#   023_1283_2600:
#     cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAatgctgNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
#     panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
#     sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  CAP409_4190:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATActatacNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
#   CAP5158_0:
#     cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAactgatNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
#     panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
#     sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
#   CAP5157_0:
#     cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAacgatcNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
#     panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
#     sec_str_primer: "TAGGCATCTCCTATGGCAGGAAGAAG"
#   CAP5143_0:
#     cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAtgaccaNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
#     panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
#     sec_str_primer: "TAGGCATCTCCTATGGCAGGAAGAAG"
#   CAP239_3090:
#     cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAgtcatcNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
#     panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
#     sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
#   CAP5123_0:
#     cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAatcacgNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
#     panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
#     sec_str_primer: "TAGGCATCTCCTATGGCAGGAAGAAG"
  CAP210_2050:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAcgatgtNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "TAGGCATCTCCTATGGCAGGAAGAAG"
#   CAP5122_0:
#     cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAacagtgNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
#     panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
#     sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  CAP409_4170:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAtagcttNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "TAGGCATCTCCTATGGCAGGAAGAAG"
#   CAP5150_0:
#     cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAgctcatNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
#     panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
#     sec_str_primer: "TAGGCATCTCCTATGGCAGGAAGAAG"
  CAP045_2060:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAcgagtaNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  CAP409_3080:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAcactcaNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  CAP311_4250:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAggtagcNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
