SCV2_pool_9_Sample_A9:
  SCV2-GP-N270_A9:
    cDNA_primer: "CCGCTCCGTCCGACGCTCACTATAgctcatNNNNNNNNCCTTGCTTCAAAGTTACAGTTCCA"
    panel: "panels/SARS-CoV-2-spike_panel.fasta"
    sec_str_primer: "GTGATGTTCTTGTTAACAACTAAACGAACA"
  SCV2-GS-H908_A14:
    cDNA_primer: "CCGCTCCGTCCGACGCTCACTATAgtcatcNNNNNNNNCCTTGCTTCAAAGTTACAGTTCCA"
    panel: "panels/SARS-CoV-2-spike_panel.fasta"
    sec_str_primer: "GTGATGTTCTTGTTAACAACTAAACGAACA"
