pool9_nicd:
  CAP261_6070:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAtagcttNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  # CAP315_4170:
  #   cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAtagagcNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
  #   panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
  #   sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  CAP292_6120:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAtgaccaNNNNNNNNCTGGTGTGTARTTYTGCCARTCAG"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "TAGGCATCTCCTATGGCAGGAAGAAG"
  CAP319_6060:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAgctcatNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  CAP264_6090:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATActatacNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  CAP228_6070:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAggtagcNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  CAP361_6070:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAacgatcNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  CAP407_6110:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAcgagtaNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  CAP292_6000:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAgtcatcNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  # CAP315_4180:
  #   cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAgacagaNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
  #   panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
  #   sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  CAP228_6000:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAacagtgNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  CAP319_6071:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAcgatgtNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  CAP221_6080:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAcactcaNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "GGCTTAGGCATCTCCTATAGCAGGAAGAA"
  CAP283_6060:
    cDNA_primer: "CCGCTCCGTCCGACGACTCACTATAatcacgNNNNNNNNGGTCTTAAAGGYACCTGAGGTCTGACTGGAAAGCC"
    panel: "panels/HIV1_COM_2017_5970-9012_DNA_stripped.fasta"
    sec_str_primer: "TAGGCATCTCCTATGGCAGGAAGAAG"
